version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=blogadmin
      - POSTGRES_PASSWORD=postgres-password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongadmin
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 27017:27017
    volumes:
      - mongodata:/mongodb/data

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - ./data:/minio/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /minio/data

volumes:
  db:
    driver: local
  mongodata:
    driver: local
